services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: agrotech-backend:1.0
    container_name: agrotech-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
    image: agrotech-frontend:1.0
    container_name: agrotech-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped